name: sceneview_flutter
description: Flutter plugin for SceneView AR - load 3D models in augmented reality with hit testing, animations, anchors, and gesture support.
version: 0.1.0
homepage: https://github.com/SceneView

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.github.sceneview.sceneview_flutter
        pluginClass: SceneviewFlutterPlugin
